import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/components/**/*.{js,ts,jsx,tsx}",
    "../../packages/ui/lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-geist-sans)", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
      },
      colors: {
        /* Semantic colors - 4-step tint scale from CSS variables */
        red: {
          50: "var(--color-red-25)",
          100: "var(--color-red-25)",
          200: "var(--color-red-50)",
          300: "var(--color-red-50)",
          400: "var(--color-red-75)",
          500: "var(--color-red-75)",
          600: "var(--color-red-100)",
          700: "var(--color-red-100)",
          800: "var(--color-red-100)",
          900: "var(--color-red-100)",
          950: "var(--color-red-100)",
        },
        orange: {
          50: "var(--color-orange-25)",
          100: "var(--color-orange-25)",
          200: "var(--color-orange-50)",
          300: "var(--color-orange-50)",
          400: "var(--color-orange-75)",
          500: "var(--color-orange-75)",
          600: "var(--color-orange-100)",
          700: "var(--color-orange-100)",
          800: "var(--color-orange-100)",
          900: "var(--color-orange-100)",
          950: "var(--color-orange-100)",
        },
        yellow: {
          50: "var(--color-yellow-25)",
          100: "var(--color-yellow-25)",
          200: "var(--color-yellow-50)",
          300: "var(--color-yellow-50)",
          400: "var(--color-yellow-75)",
          500: "var(--color-yellow-75)",
          600: "var(--color-yellow-100)",
          700: "var(--color-yellow-100)",
          800: "var(--color-yellow-100)",
          900: "var(--color-yellow-100)",
          950: "var(--color-yellow-100)",
        },
        green: {
          50: "var(--color-green-25)",
          100: "var(--color-green-25)",
          200: "var(--color-green-50)",
          300: "var(--color-green-50)",
          400: "var(--color-green-75)",
          500: "var(--color-green-75)",
          600: "var(--color-green-100)",
          700: "var(--color-green-100)",
          800: "var(--color-green-100)",
          900: "var(--color-green-100)",
          950: "var(--color-green-100)",
        },
        blue: {
          50: "var(--color-blue-25)",
          100: "var(--color-blue-25)",
          200: "var(--color-blue-50)",
          300: "var(--color-blue-50)",
          400: "var(--color-blue-75)",
          500: "var(--color-blue-75)",
          600: "var(--color-blue-100)",
          700: "var(--color-blue-100)",
          800: "var(--color-blue-100)",
          900: "var(--color-blue-100)",
          950: "var(--color-blue-100)",
        },
        purple: {
          50: "var(--color-purple-25)",
          100: "var(--color-purple-25)",
          200: "var(--color-purple-50)",
          300: "var(--color-purple-50)",
          400: "var(--color-purple-75)",
          500: "var(--color-purple-75)",
          600: "var(--color-purple-100)",
          700: "var(--color-purple-100)",
          800: "var(--color-purple-100)",
          900: "var(--color-purple-100)",
          950: "var(--color-purple-100)",
        },
        /* Neutral scale for UI chrome */
        neutral: {
          50: "var(--color-neutral-50)",
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
          700: "var(--color-neutral-700)",
          800: "var(--color-neutral-800)",
          900: "var(--color-neutral-900)",
          925: "var(--color-neutral-925)",
          950: "var(--color-neutral-950)",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};

export default config;

