/**
 * Monthly Summary Email
 * Sent to business owner on the 1st of each month with stats
 */

export interface MonthlySummaryEmailProps {
  businessName: string;
  month: string; // e.g., "December 2024"
  newMembers: number;
  churned: number;
  totalActiveMembers: number;
  revenue: number;
  currency: string;
  topPlan?: string;
  dashboardUrl: string;
}

export function MonthlySummaryEmail(props: MonthlySummaryEmailProps): string {
  const { 
    businessName, 
    month, 
    newMembers, 
    churned, 
    totalActiveMembers, 
    revenue, 
    currency, 
    topPlan,
    dashboardUrl 
  } = props;
  
  const netGrowth = newMembers - churned;
  const growthColor = netGrowth >= 0 ? "#10b981" : "#ef4444";
  const growthSign = netGrowth >= 0 ? "+" : "";
  
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Monthly Summary - ${month}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; border-radius: 8px 8px 0 0;">
    <h1 style="color: white; margin: 0;">${month} Summary</h1>
    <p style="color: rgba(255,255,255,0.9); margin: 10px 0 0 0;">${businessName}</p>
  </div>
  
  <div style="background: #f9fafb; padding: 30px; border-radius: 0 0 8px 8px;">
    <p style="font-size: 16px; margin-bottom: 20px;">Here's how your wine club performed last month:</p>
    
    <!-- Stats Grid -->
    <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 20px 0;">
      <div style="background: white; padding: 20px; border-radius: 8px; text-align: center;">
        <p style="font-size: 32px; font-weight: bold; color: #10b981; margin: 0;">${newMembers}</p>
        <p style="font-size: 14px; color: #666; margin: 5px 0 0 0;">New Members</p>
      </div>
      <div style="background: white; padding: 20px; border-radius: 8px; text-align: center;">
        <p style="font-size: 32px; font-weight: bold; color: #ef4444; margin: 0;">${churned}</p>
        <p style="font-size: 14px; color: #666; margin: 5px 0 0 0;">Cancelled</p>
      </div>
      <div style="background: white; padding: 20px; border-radius: 8px; text-align: center;">
        <p style="font-size: 32px; font-weight: bold; color: #667eea; margin: 0;">${totalActiveMembers}</p>
        <p style="font-size: 14px; color: #666; margin: 5px 0 0 0;">Active Members</p>
      </div>
      <div style="background: white; padding: 20px; border-radius: 8px; text-align: center;">
        <p style="font-size: 32px; font-weight: bold; color: #667eea; margin: 0;">$${(revenue / 100).toFixed(0)}</p>
        <p style="font-size: 14px; color: #666; margin: 5px 0 0 0;">Revenue</p>
      </div>
    </div>
    
    <!-- Net Growth -->
    <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid ${growthColor};">
      <h3 style="margin-top: 0; color: #333;">Net Growth</h3>
      <p style="font-size: 24px; font-weight: bold; color: ${growthColor}; margin: 10px 0;">
        ${growthSign}${netGrowth} members
      </p>
      ${topPlan ? `<p style="font-size: 14px; color: #666; margin: 10px 0 0 0;"><strong>Top Plan:</strong> ${topPlan}</p>` : ''}
    </div>
    
    <div style="text-align: center; margin: 30px 0;">
      <a href="${dashboardUrl}" style="display: inline-block; background: #667eea; color: white; padding: 14px 28px; text-decoration: none; border-radius: 6px; font-weight: 600;">View Full Analytics</a>
    </div>
    
    <p style="font-size: 14px; color: #666; margin-top: 30px;">
      Keep up the great work! Your wine club is growing.
    </p>
    
    <p style="font-size: 12px; color: #999; margin-top: 30px;">
      This summary was generated by Vintigo Platform
    </p>
  </div>
</body>
</html>
  `;
}

export const monthlySummaryEmail = MonthlySummaryEmail;
